
#This script install couchdb Start couchdb

#try to run a script
#- name: Transfer and execute a script.
#  become: yes
#  script: /Users/liuyongkang/Desktop/project/venv/test.sh
#  register: out

#- debug: var=out.stdout_lines

#create a dir for data storage under ~/
- file:
    path: /home/ubuntu/couchDB
    state: directory
    mode: 0755
    
- name: Create a ext4 filesystem on /dev/vdb and check disk blocks
  become: yes
  filesystem:
    fstype: ext4
    dev: /dev/vdb

#now mount all /dev/vdc to ~/couchDB
- name: Mount up device
  become: yes
  mount:
    path: /home/ubuntu/couchDB
    src: /dev/vdb
    fstype: ext4
    state: mounted


#pull docker io
- name: Update repositories cache and install docker.io package
  become: yes
  apt:
    name: docker.io
    update_cache: yes

- name: 'make ubuntu a owner of docker too'
  become: yes
  command: usermod -a -G docker ubuntu


- name: 'install VIM'
  become: yes 
  command: sudo apt-get install -y vim
  register: out
- debug: var=out.stdout_lines

#to upload and run

- name: COPY part one of shell script to every node
  copy:
    src: /Users/liuyongkang/Desktop/project/venv/shell/setup1.sh
    dest: /home/ubuntu/setup1.sh
    owner: ubuntu
    group: ubuntu
    mode: 0644


- name: 'Make the script runnable'
  become: yes 
  command: sudo chmod +x setup1.sh
  register: out
- debug: var=out.stdout_lines


- name: example copying file with owner and permissions
  copy:
    src: /Users/liuyongkang/Desktop/project/venv/shell/setup2.sh
    dest: /home/ubuntu/setup2.sh
    owner: ubuntu
    group: ubuntu
    mode: 0644


- name: 'Make the script runnable'
  become: yes 
  command: sudo chmod +x setup2.sh
  register: out
- debug: var=out.stdout_lines

#THIS IS FOR MAINDBNODE ROLE
- name: 'Run the script to configure couchdb using docker'
  become: yes 
  command: ./setup1.sh
  register: out
- debug: var=out.stdout_lines

#THIS IS FOR MAINDBNODE ROLE
- name: 'Run the script to configure couchdb using docker'
  become: yes 
  command: ./setup2.sh
  register: out
- debug: var=out.stdout_lines


